import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-slate-50 text-slate-900 relative min-h-[100dvh] selection:bg-blue-200 selection:text-blue-900 overflow-x-hidden">
        {/* Global SVG Noise Overlay */}
        <div className="fixed inset-0 z-[100] pointer-events-none bg-noise" />
        
        {/* Subtle Grid */}
        <div className="fixed inset-0 -z-20 h-full w-full bg-[linear-gradient(to_right,#80808008_1px,transparent_1px),linear-gradient(to_bottom,#80808008_1px,transparent_1px)] bg-[size:24px_24px]"></div>
        
        {/* Vibrant Floating Orbs */}
        <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
           <div className="absolute top-[-15%] left-[-10%] w-[60%] h-[60%] rounded-full bg-gradient-to-tr from-blue-400/30 to-fuchsia-400/30 blur-[140px] animate-blob" />
           <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] rounded-full bg-gradient-to-bl from-indigo-400/30 to-cyan-300/30 blur-[140px] animate-blob animation-delay-2000" />
           <div className="absolute top-[20%] right-[15%] w-[40%] h-[40%] rounded-full bg-gradient-to-r from-emerald-400/20 to-teal-300/20 blur-[120px] animate-blob animation-delay-4000" />
        </div>
        {children}
      </body>
    </html>
  );
}
